# Generated by Django 4.2.3 on 2023-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='account_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='branch_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='ifsc',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
