# Generated by Django 4.2.3 on 2023-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='country',
        ),
    ]
