# Generated by Django 4.2.3 on 2023-07-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_seller_account_no_seller_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='login_id',
            field=models.IntegerField(null=True),
        ),
    ]
