# Generated by Django 4.2.3 on 2023-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_seller_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
