# Generated by Django 4.2.3 on 2023-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_land_mark_deliveryaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='landmark',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
