# Generated by Django 4.2.3 on 2023-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
