# Generated by Django 4.2.3 on 2023-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_productreview_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
