# Generated by Django 4.2.3 on 2023-08-07 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
