# Generated by Django 4.2.3 on 2023-08-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_productquestion_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
