# Generated by Django 4.2.3 on 2023-08-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_answers_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
