# Generated by Django 4.2.3 on 2023-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='order placed', max_length=100),
        ),
    ]
