# Generated by Django 4.2.3 on 2023-08-11 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_remove_order_order_status_remove_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
