# Generated by Django 4.2.3 on 2023-08-11 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_orderitem_delivered_date_orderitem_delivery_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_out',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='packed_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
