# Generated by Django 4.2.3 on 2023-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_orderitem_cancelled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
