# Generated by Django 4.2.3 on 2023-08-11 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_orderitem_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_changed_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
