# Generated by Django 4.2.3 on 2023-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_customer_last_changed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
