# Generated by Django 4.2.3 on 2023-08-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_customer_is_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_changed',
            new_name='is_password_changed',
        ),
    ]
