# Generated by Django 4.2.3 on 2023-07-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_seller_company_name'),
        ('eKart_admin', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=20)),
                ('decription', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eKart_admin.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.seller')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
