# Generated by Django 4.2.3 on 2023-08-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.FloatField(default=2.1),
        ),
    ]
