# Generated by Django 4.2.3 on 2023-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_decription_product_description_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
