# Generated by Django 4.2.3 on 2023-08-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='rating',
        ),
    ]
