# Generated by Django 4.2.3 on 2023-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_review_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
